-- Up Migration: Remove time zone from relevant columns
ALTER TABLE cron_job_audit_logs
    ALTER COLUMN scheduled_time TYPE TIMESTAMP WITHOUT TIME ZONE,
    ALTER COLUMN start_time TYPE TIMESTAMP WITHOUT TIME ZONE,
    ALTER COLUMN end_time TYPE TIMESTAMP WITHOUT TIME ZONE,
    ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE,
    ALTER COLUMN updated_at TYPE TIMESTAMP WITHOUT TIME ZONE;