// Package cron provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package cron

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Job defines model for Job.
type Job struct {
	Id                openapi_types.UUID `json:"id"`
	LastExecutionTime *time.Time         `json:"last_execution_time,omitempty"`
	LockedAt          *time.Time         `json:"locked_at,omitempty"`
	LockedBy          *string            `json:"locked_by,omitempty"`
	Name              string             `json:"name"`
	NextExecutionTime *time.Time         `json:"next_execution_time,omitempty"`
	Status            string             `json:"status"`
}

// JobAuditLog defines model for JobAuditLog.
type JobAuditLog struct {
	AppId         string             `json:"app_id"`
	CreatedAt     time.Time          `json:"createdAt"`
	EndTime       *time.Time         `json:"end_time,omitempty"`
	Error         *string            `json:"error,omitempty"`
	Id            openapi_types.UUID `json:"id"`
	JobName       string             `json:"job_name"`
	Output        *string            `json:"output,omitempty"`
	RequestId     string             `json:"request_id"`
	ScheduledTime time.Time          `json:"scheduled_time"`
	StartTime     *time.Time         `json:"start_time,omitempty"`
	Status        string             `json:"status"`
	TenantID      string             `json:"tenantID"`
	UpdatedAt     *time.Time         `json:"updatedAt,omitempty"`
}

// NewJob defines model for NewJob.
type NewJob struct {
	LastExecutionTime *time.Time `json:"last_execution_time,omitempty"`
	LockedAt          *time.Time `json:"locked_at,omitempty"`
	LockedBy          *string    `json:"locked_by,omitempty"`
	Name              string     `json:"name"`
	NextExecutionTime *time.Time `json:"next_execution_time,omitempty"`
	Status            string     `json:"status"`
}

// RegisteredJob defines model for RegisteredJob.
type RegisteredJob struct {
	// CreatedAt When the job was first registered
	CreatedAt time.Time `json:"created_at"`

	// Description Human-readable description of the job
	Description *string `json:"description,omitempty"`

	// Id Unique identifier for the job
	Id openapi_types.UUID `json:"id"`

	// InstanceId ID of the instance that registered the job
	InstanceId string `json:"instance_id"`

	// IsEnabled Whether the job is enabled
	IsEnabled bool `json:"is_enabled"`

	// IsLongRunning Whether this is a long-running job that needs heartbeats
	IsLongRunning bool `json:"is_long_running"`

	// JobName Name of the job
	JobName string `json:"job_name"`

	// LastRegisteredAt When the job was last registered
	LastRegisteredAt time.Time `json:"last_registered_at"`

	// Schedule Cron schedule expression
	Schedule string `json:"schedule"`

	// TenantId Tenant ID the job belongs to
	TenantId string `json:"tenant_id"`

	// UpdatedAt When the job was last updated
	UpdatedAt time.Time `json:"updated_at"`
}
