// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CronJob struct {
	ID                uuid.UUID          `json:"id"`
	Lock              string             `json:"lock"`
	JobName           string             `json:"job_name"`
	Status            string             `json:"status"`
	LastExecutionTime pgtype.Timestamptz `json:"last_execution_time"`
	NextExecutionTime pgtype.Timestamptz `json:"next_execution_time"`
	LockedBy          pgtype.Text        `json:"locked_by"`
	LockedAt          pgtype.Timestamptz `json:"locked_at"`
	TenantID          string             `json:"tenant_id"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         time.Time          `json:"updated_at"`
}

type CronJobAuditLog struct {
	ID            uuid.UUID        `json:"id"`
	AppID         string           `json:"app_id"`
	RequestID     string           `json:"request_id"`
	JobName       string           `json:"job_name"`
	ScheduledTime pgtype.Timestamp `json:"scheduled_time"`
	StartTime     pgtype.Timestamp `json:"start_time"`
	EndTime       pgtype.Timestamp `json:"end_time"`
	Status        string           `json:"status"`
	Output        pgtype.Text      `json:"output"`
	Error         pgtype.Text      `json:"error"`
	UserID        string           `json:"user_id"`
	TenantID      string           `json:"tenant_id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type CronRegisteredJob struct {
	ID               uuid.UUID `json:"id"`
	JobName          string    `json:"job_name"`
	Schedule         string    `json:"schedule"`
	IsLongRunning    bool      `json:"is_long_running"`
	IsEnabled        bool      `json:"is_enabled"`
	LastRegisteredAt time.Time `json:"last_registered_at"`
	InstanceID       string    `json:"instance_id"`
	TenantID         string    `json:"tenant_id"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}
